### PR TITLE
Last changes to index.fr

### PR DESCRIPTION
**Pull request by vmmiller**
Change log:  
Translator added: V. Menezes Miller
Contributor added: Rémi Bétin
Title changed to: Principes fondamentaux de l'accessibilité - Vue d'ensemble
Sentence modified: Les ressources suivantes fournissent des informations pour débuter en accessibilité:
Sub-heading changed to: L'accessibilité Web illustrée
Sub-heading changed to: L'Accessibilité Web pour les utilisateurs plus âgés: une revue de la littérature

### CODE REVIEW

**Comment by vmmiller** [comment]
@shawna-slh  - okay to merge.

**Comment by shawna-slh** [comment]
merged! thanks!

I didn't merge others at https://github.com/w3c/wai-fundamentals-overview/pulls to avoid overwriting again. :-/ Should those be closed or other ?

Also, you say "last". Does that mean this is ready to publish?!? https://deploy-preview-33--wai-fundamentals-overview.netlify.app/fundamentals/fr

**Comment by shawna-slh** [comment]
ah, I see you updated ready to publish in the spreadsheet! :-)

**Comment by vmmiller** [comment]
I'll check and revert on publishing.

**Pull request merged**
